print("\n===== 1. Lists =====\n")

# Ordered, mutable and allows duplicate elements
my_list = [3, 2, 1, 2, 3]
print(f"My list: {my_list}")

# Create a new empty list
# empty_list = list()

# IndexError: list index out of range
# my_list[10]

# We can get a deleted item
deleted_item = my_list.pop()
print(f"Deleted item: {deleted_item}")

# ValueError: x not in list
# my_list.remove(5)

# If you don't want to change the original list
sorted_list = sorted(my_list)
print(f"\nSorted: {sorted_list}")

# Trick to reverse a list
# By the way, slice makes an independent copy
reversed_list = sorted_list[::-1]
print(f"Reversed: {reversed_list}")
print(f"Sorted is ok: {sorted_list}")

# Create a new list with the same element multiple times
zeros = [0] * 10
print(f"\nGenerated by an expression: {zeros}")

# Create a new list using an expression
sevens = [i + 7 for i in zeros]
print(f"Changed by an expression: {sevens}")


print("\n===== 2. Tuples =====\n")

# Immutable list
# Parentheses are optional
accesses = "ADMIN", "USER"
print(f"{accesses} \n{type(accesses)}\n")

# A single item is not recognized as a tuple
strongest = "Gojo"
print(f"{strongest} \n{type(strongest)}\n")

# That's why you should add an extra comma
strongest = ("Gojo",)
print(f"{strongest} \n{type(strongest)}\n")

# Build-in tuple function
# It works in two ways
sevens_tuple = tuple(sevens)
print(f"Converted list: {sevens_tuple}")

# ValueError: x not in tuple
# sevens_tuple.index(6)

# By the way, we can slice a tuple
sevens_slice = sevens_tuple[:5]
print(f"Sliced tuple: {sevens_slice}")

# Unpacking with an asterisk
item, *items = sevens_slice
print(f"\nDefault unpacking: {item}")
print(f"Advanced unpacking: {items}")
